name: Windows - LiteManager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Downloading & Installing Essentials
        run: |
          cmd /c Downloads.bat

      - name: Connect to LiteManager
        run: |
          cmd /c show.bat

      - name: Time Counter
        run: |
          cmd /c loop.bat
